In [9]:
import numpy as np

a = np.random.rand(5)
a = a.reshape(5,1)

In [10]:
print(a) # menampilkan data random (vector)

[[0.18233867]
 [0.46693906]
 [0.46902487]
 [0.93488026]
 [0.15844163]]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[0.58280431 0.41515365 0.91091721 0.48773021 0.82247859]


In [5]:
print(np.dot(a, a.T))

2.2561353654807874


In [6]:
d = np.random.randn(5,1)
print(d)

[[-0.781075  ]
 [ 1.3668419 ]
 [ 0.75234814]
 [-1.38687168]
 [ 0.83304158]]


In [7]:
print(d.T)

[[-0.781075    1.3668419   0.75234814 -1.38687168  0.83304158]]


In [8]:
print(np.dot(d, d.T))

[[ 0.61007816 -1.06760604 -0.58764032  1.0832508  -0.65066795]
 [-1.06760604  1.86825677  1.02834096 -1.89563432  1.13863613]
 [-0.58764032  1.02834096  0.56602772 -1.04341032  0.62673728]
 [ 1.0832508  -1.89563432 -1.04341032  1.92341306 -1.15532177]
 [-0.65066795  1.13863613  0.62673728 -1.15532177  0.69395827]]
